[package]
name = "fit_reader"
version = "0.1.0"
authors = ["John Stark <jhnstrk@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
byteorder = "1.3.1"
serde_json = "1.0.38"
serde = "1.0.88"
serde_derive = "1.0.88"
chrono = "0.4.6"
