[package]
name = "fit_reader"
version = "0.1.0"
authors = ["John Stark <jhnstrk@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
byteorder = "1.4.3"
serde_json = "1.0.81"
serde = "1.0.137"
serde_derive = "1.0.137"
chrono = "0.4.19"
log = "0.4.17"
env_logger = "0.9.0"
